# service monitor config file

# file for datastore - keeps track of ongoing downtimes
datastore: "store.db"

# time to delay between re-checking failed sites
# to help stop notifying on momentary net issues on the checking machine
recheck-delay: "10s"

# ongoing issues, where we continually detect downtimes
ongoing:
    # number of alerts to do in a row when we first detect problems
    initial-max-alerts: 3

    # after the initial burst, how long to wait between each notification
    ongoing-delay: 20m

# notify targets and configuration
notify:
    # default targets for our notifications
    default-targets:
        # australian phone numbers to send notices to
        sms-telstra:
            - "0123456789"
            - "0987654321"

        # email addresses to send notices to
        email:
            -
                name: "Test User"
                address: test@example.com
            -
                name: "Test User 5"
                address: test5@example.com

    # sms notifications sent with Telstra
    sms-telstra:
        # sms app key
        key: app-key-here

        # sms app secret
        secret: app-secret-here

    # email notifications via Sendgrid API
    email-sendgrid:
        # from email name
        from-name: "Status Monitor"

        # from email address
        from-address: monitor@example.com

        # Sendgrid API key
        api-key: abcd1234

# services to monitor
services:
    # websites / URLs
    web:
        "ABC Website":
            url: https://example.com/
            # test once with each given user agent, useful for testing desktop + mobile at the same time
            user-agents:
                - "Mozilla/5.0 (Windows NT x.y; Win64; x64; rv:10.0) Gecko/20100101 Firefox/10.0"
                - "Mozilla/6.0 (iPhone; CPU iPhone OS 8_0 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/8.0 Mobile/10A5376e Safari/8536.25"
            matches:
                - "used for illustrative examples"
                - "use this domain in examples without prior coordination or asking for permission"
        "ABC Blog":
            url: https://blog.example.com/
                - "News on the example market"
                - "More information"
        "ABC Blog - Mobile Theme":
            user-agent: "Mozilla/6.0 (iPhone; CPU iPhone OS 8_0 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/8.0 Mobile/10A5376e Safari/8536.25"
            url: https://blog.example.com/
                - "News on the example market"
                - "More information"
    # socks5 proxy
    socks5:
        "ABC SOCKS5 Proxy":
            # hostname / port
            host: proxy.example.com
            port: 1080

            # how many launches of downtimealert we should wait between every check that we do.
            # this is primarily useful when, i.e. cronning it every one minute, in order to slow down login attempts.
            wait-between-attempts: 5

            # credentials to access the proxy. if there are more than one set, we run through them one-by-one on each launch.
            credentials:
                -
                    username: x1234567
                    password: qwertyuiop
                -
                    username: x7654321
                    password: poiuytrewq

            # page to download to test connections
            test-download:
                # url to download
                # {{random-int}} will be replaced with a random integer if it exists, intended to bypass caches
                url: http://www.example.com/index.html?test={{random-int}}

                # max size to download
                max-size-to-dl: 2Mb

                # service level objectives we want to achieve, and respectively those that we alert on
                slo:
                    # how long to retain history (to calculate targets from)
                    # like:  5h12m37s
                    history-retained: 30m

                    # how many failures in a row before we start alerting people
                    max-failures-in-a-row: 3

                    # what uptime do we expect.
                    # covers auth failures, just not being able to access it, etc.
                    # if they can get to d/ling (below), it's not an uptime failure.
                    # 0.25 == 25%, etc
                    # SOCKS5 proxy runs hot, so we can expect a reasonable amount of failures.
                    uptime-target: 0.5

                    # minimum speed per second we expect
                    min-speed-per-second: 500Kb

                    # how many of our tests do we expect to be over the min speed
                    # 0.25 == 25%, etc
                    speed-target: 0.7
