# service monitor config file

# file for datastore - keeps track of ongoing downtimes
datastore: "store.db"

# time to delay between re-checking failed sites
# to help stop notifying on momentary net issues on the checking machine
recheck-delay: "10s"

# ongoing issues, where we continually detect downtimes
ongoing:
    # number of alerts to do in a row when we first detect problems
    initial-max-alerts: 3

    # after the initial burst, how long to wait between each notification
    ongoing-delay: 20m

# notify targets and configuration
notify:
    # default targets for our notifications
    default-targets:
        # australian phone numbers to send notices to
        sms-telstra:
            - "0123456789"
            - "0987654321"

        # email addresses to send notices to
        email:
            -
                name: "Test User"
                address: test@example.com
            -
                name: "Test User 5"
                address: test5@example.com

    # sms notifications sent with Telstra
    sms-telstra:
        # sms app key
        key: app-key-here

        # sms app secret
        secret: app-secret-here

    # email notifications via Sendgrid API
    email-sendgrid:
        # from email name
        from-name: "Status Monitor"

        # from email address
        from-address: monitor@example.com

        # Sendgrid API key
        api-key: abcd1234

# services to monitor
services:
    # websites / URLs
    web:
        "ABC Website":
            url: https://example.com/
        "ABC Blog":
            url: https://blog.example.com/
    # socks5 proxy
    socks5:
        "ABC SOCKS5 Proxy":
            # hostname / port
            host: proxy.example.com
            port: 1080

            # credentials to access the proxy. if there are more than one set, we run through them one-by-one on each launch.
            credentials:
                -
                    username: x1234567
                    password: qwertyuiop
                -
                    username: x7654321
                    password: poiuytrewq

            # domain to test connections with
            test-domain: example.com